### ISSUE TITLE
Wrong namespace in documentation

### ISSUE THREAD

**Issue by ignatandrei** [shawnwildermuth/MinimalApis#1]
Hello

The namespace at 

https://github.com/shawnwildermuth/MinimalApis/blob/main/MinimalApis.Discovery.md

 should be modified from
```csharp
using WilderMinds.MinimalApiDiscovery;

namespace UsingMinimalApiDiscovery.Apis;

public class StateApi : IApi
```

to

```csharp
using MinimalApis.Discovery;
```

( that is where MinimalApisDiscoveryGeneratedExtensions class is generated )

( I discovered this because I have made an example with MinimalApis.Discovery at https://ignatandrei.github.io/RSCG_Examples/v2/docs/MinimalApis.Discovery

**Comment by shawnwildermuth** [comment]
Good catch!
